global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts/chatty.yaml

scrape_configs:
  - job_name: chatty-server
    metrics_path: /metrics
    static_configs:
      - targets: ["chatty-server:18208"]
